apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdfghjkjhgfdsasdfghjkl
  labels:
    app: asdfghjkjhgfdsasdfghjkl
  namespace: namespace-workflow-1690454439625
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdfghjkjhgfdsasdfghjkl
  template:
    metadata:
      labels:
        app: asdfghjkjhgfdsasdfghjkl
    spec:
      containers:
        - name: asdfghjkjhgfdsasdfghjkl
          image: noushadregistry.azurecr.io/image-workflow-1690454439625:latest
          ports:
            - containerPort: 3000