apiVersion: v1
kind: Service
metadata:
  name: new
  namespace: namespace-workflow-1690453475159
spec:
  type: LoadBalancer
  selector:
    app: new
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000